apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgresql
  namespace: postgresql
spec:
  storageClassName: gp2 
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
