apiVersion: v1
kind: Secret
metadata:
  name: secret-postgresql
  namespace: postgresql
type: Opaque
data:
  POSTGRES_DB: aWJtZGI=
  POSTGRES_USER: aWJtYWRtaW4= 
  POSTGRES_PASSWORD: aWJtcGFzc3dvcmQ= 
