apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: postgresql
  labels:
    app: postgresql
spec:
  ports:
  - port: 5432
    name: postgres
  selector:
    app: postgresql
